name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy the content
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      # Remove unnecessary files from deployment
      - name: Remove unnecessary files
        run: |
          rm -r .git
          rm -r .github
          rm README.md
      - name: Install sshpass
        run: sudo apt install sshpass
      # Zip content and send to the server and unzip in the server
      - name: SSH files to the server
        run: tar -c ./ | sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} "tar -xvf - -C /var/ghTest/html" 
      # https://github.com/marketplace/actions/copy-via-ssh         
#       - name: Copy content recursively to remote
#         uses: garygrossgarten/github-action-scp@release
#         with:
#           local: ./
#           remote: /var/www/html
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.SSH_USER }}
#           password: ${{ secrets.PASSWORD }}
#           tryKeyboard: false
#           rmRemote: false
